##NumPy Laboratory Practice Questions

##1. Array Creation & Properties

1.	Create a NumPy array from [10, 20, 30, 40, 50]. Display its shape, size, and data type.

In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print("Array:", arr)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data Type:", arr.dtype)

Array: [10 20 30 40 50]
Shape: (5,)
Size: 5
Data Type: int64


2.	Create a 3 × 4 array containing numbers from 1 to 12.

In [2]:
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


3.	Create an array of zeros, an array of ones, and an identity matrix.

In [3]:
import numpy as np

zeros = np.zeros(5)
ones = np.ones(5)
identity = np.eye(3)

print("Zeros:", zeros)
print("Ones:", ones)
print("Identity Matrix:")
print(identity)

Zeros: [0. 0. 0. 0. 0.]
Ones: [1. 1. 1. 1. 1.]
Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4.	Generate all even numbers between 10 and 50 using np.arange().

In [4]:
import numpy as np

arr = np.arange(10, 51, 2)

print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


5.	Create an array of 10 equally spaced numbers between 0 and 1 using np.linspace().

In [5]:
import numpy as np

arr = np.linspace(0, 1, 10)

print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


##2. Array Arithmetic

6.	Given two NumPy arrays, perform element-wise addition, subtraction, multiplication, and division.

In [6]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([2, 4, 6])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [12 24 36]
Subtraction: [ 8 16 24]
Multiplication: [ 20  80 180]
Division: [5. 5. 5.]


7.	Calculate the square and cube of every element in a NumPy array.

In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print("Square:", arr ** 2)
print("Cube:", arr ** 3)

Square: [ 1  4  9 16 25]
Cube: [  1   8  27  64 125]


8.	Increase every element of an array by 15%.

In [8]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

result = arr * 1.15

print(result)

[11.5 23.  34.5 46.  57.5]


9.	Given two arrays, find their element-wise maximum and minimum.

In [9]:
import numpy as np

a = np.array([10, 25, 15, 40])
b = np.array([20, 15, 30, 35])

print("Maximum:", np.maximum(a, b))
print("Minimum:", np.minimum(a, b))

Maximum: [20 25 30 40]
Minimum: [10 15 15 35]


##3. Indexing & Slicing

10.	Create an array from 0 to 20 and extract the first five elements, last five elements, elements from index 5 to 15, and every second element.

In [11]:
import numpy as np

arr = np.arange(21)

print("First five:", arr[:5])
print("Last five:", arr[-5:])
print("Index 5 to 15:", arr[5:16])
print("Every second element:", arr[::2])

First five: [0 1 2 3 4]
Last five: [16 17 18 19 20]
Index 5 to 15: [ 5  6  7  8  9 10 11 12 13 14 15]
Every second element: [ 0  2  4  6  8 10 12 14 16 18 20]


11.	Replace the first five elements of an array with 100.

In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

arr[:5] = 100

print(arr)

[100 100 100 100 100   6   7   8]


12.	Create an array and demonstrate the difference between a slice/view and a copy.

In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

view = arr[:3]
copy = arr[:3].copy()

view[0] = 100
copy[1] = 200

print("Original:", arr)
print("View:", view)
print("Copy:", copy)

# View: Changes the original array.
# Copy: Does not change the original array.

Original: [100   2   3   4   5]
View: [100   2   3]
Copy: [  1 200   3]


13.	Reverse a NumPy array using slicing.

In [14]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr[::-1])

[5 4 3 2 1]


##4. 2-D Array Indexing & Slicing

14.	Create the matrix [[10,20,30],[40,50,60],[70,80,90]]. Extract the second row, third column, and element 50.

In [15]:
import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

print("Second row:", arr[1])
print("Third column:", arr[:, 2])
print("Element 50:", arr[1, 1])

Second row: [40 50 60]
Third column: [30 60 90]
Element 50: 50


15.	From the matrix above, extract the sub-matrix [[20,30],[50,60]].

In [16]:
import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

print(arr[0:2, 1:3])

[[20 30]
 [50 60]]


16.	Create a 5 × 5 matrix containing 1–25 and extract the first row, last column, middle element, and top-left 3 × 3 matrix.

In [17]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20],
                [21, 22, 23, 24, 25]])

print("First row:", arr[0])
print("Last column:", arr[:, 4])
print("Middle element:", arr[2, 2])
print("Top-left 3x3:")
print(arr[0:3, 0:3])

First row: [1 2 3 4 5]
Last column: [ 5 10 15 20 25]
Middle element: 13
Top-left 3x3:
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


##5. Reshaping & Transpose

17.	Create an array containing 1–12 and reshape it into a 3 × 4 matrix.

In [18]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

matrix = arr.reshape(3, 4)

print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


18.	Reshape a 1-D array into a 2 × 5 matrix.

In [19]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

matrix = arr.reshape(2, 5)

print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


19.	Convert a 3 × 4 matrix into a 4 × 3 matrix using transpose.

In [20]:
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print(arr.T)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


20.	Use transpose() and swapaxes() on a 3-D array.

In [21]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]],
                [[5, 6], [7, 8]]])

print("Transpose:")
print(arr.transpose())

print("Swapaxes:")
print(arr.swapaxes(0, 1))

Transpose:
[[[1 5]
  [3 7]]

 [[2 6]
  [4 8]]]
Swapaxes:
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


#6. Matrix Operations

21.	Create two 3 × 3 matrices and perform element-wise addition and multiplication.

In [22]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

b = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

print("Addition:")
print(a + b)

print("Multiplication:")
print(a * b)

Addition:
[[10 10 10]
 [10 10 10]
 [10 10 10]]
Multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


22.	Calculate the matrix product of two compatible matrices using np.dot().

In [23]:
import numpy as np

a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

result = np.dot(a, b)

print(result)

[[19 22]
 [43 50]]


23.	Find the transpose of a matrix and calculate its dot product with the original matrix.

In [24]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

transpose = arr.T

print("Transpose:")
print(transpose)

print("Dot Product:")
print(np.dot(transpose, arr))

Transpose:
[[1 4]
 [2 5]
 [3 6]]
Dot Product:
[[17 22 27]
 [22 29 36]
 [27 36 45]]


#7. Universal Functions

24.	Calculate the square root of every element in an array using NumPy.

In [25]:
import numpy as np

arr = np.array([1, 4, 9, 16, 25])

print(np.sqrt(arr))

[1. 2. 3. 4. 5.]


25.	Calculate e^x for every element of an array.

In [26]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(np.exp(arr))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


26.	Generate a random array and calculate its square root, exponential, and absolute values.

In [28]:
import numpy as np

arr = np.random.rand(5)

print("Array:", arr)
print("Square root:", np.sqrt(arr))
print("Exponential:", np.exp(arr))
print("Absolute:", np.abs(arr))

Array: [0.89522133 0.78099785 0.78770666 0.37996793 0.93331224]
Square root: [0.94616137 0.88374083 0.8875284  0.61641538 0.96608087]
Exponential: [2.44787752 2.18365014 2.19834908 1.46223769 2.542918  ]
Absolute: [0.89522133 0.78099785 0.78770666 0.37996793 0.93331224]


27.	Generate two random arrays and find their element-wise maximum.

In [29]:
import numpy as np

a = np.random.rand(5)
b = np.random.rand(5)

print("Array 1:", a)
print("Array 2:", b)
print("Maximum:", np.maximum(a, b))

Array 1: [0.47115686 0.61427546 0.40406773 0.52218851 0.06490521]
Array 2: [0.62900922 0.60800269 0.08053719 0.13768632 0.82091506]
Maximum: [0.62900922 0.61427546 0.40406773 0.52218851 0.82091506]


#8. np.where()

28.	Given marks = np.array([35,72,48,90,55,28]), replace marks below 40 with 0 using np.where().

In [30]:
import numpy as np

marks = np.array([35, 72, 48, 90, 55, 28])

marks = np.where(marks < 40, 0, marks)

print(marks)

[ 0 72 48 90 55  0]


29.	Given an income array, classify observations as 'High' if income ≥ 50,000 and 'Low' otherwise.

In [31]:
import numpy as np

income = np.array([30000, 55000, 45000, 70000, 50000])

result = np.where(income >= 50000, "High", "Low")

print(result)

['Low' 'High' 'Low' 'High' 'High']


30.	Replace all values greater than 30 in an array with 100 using np.where().

In [32]:
import numpy as np

arr = np.array([10, 20, 35, 40, 25, 50])

arr = np.where(arr > 30, 100, arr)

print(arr)

[ 10  20 100 100  25 100]


#9. Statistical Operations

31.	Given a 3 × 3 matrix, calculate its total sum, mean, variance, and standard deviation.

In [33]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Variance:", np.var(arr))
print("Standard Deviation:", np.std(arr))

Sum: 45
Mean: 5.0
Variance: 6.666666666666667
Standard Deviation: 2.581988897471611


32.	Calculate row-wise and column-wise sums using axis.

In [34]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print("Row-wise sum:", np.sum(arr, axis=1))
print("Column-wise sum:", np.sum(arr, axis=0))

Row-wise sum: [ 6 15 24]
Column-wise sum: [12 15 18]


33.	Given the marks of 10 students, calculate mean, standard deviation, minimum, and maximum.

In [35]:
import numpy as np

marks = np.array([45, 67, 78, 56, 89, 92, 34, 76, 61, 50])

print("Mean:", np.mean(marks))
print("Standard Deviation:", np.std(marks))
print("Minimum:", np.min(marks))
print("Maximum:", np.max(marks))

Mean: 64.8
Standard Deviation: 18.115186998758805
Minimum: 34
Maximum: 92


34.	Demonstrate the difference between any() and all() using a Boolean array.

In [40]:
import numpy as np

arr = np.array([True, False, True, True])

print("Any:", np.any(arr))
print("All:", np.all(arr))

Any: True
All: False


#10. Sorting & Unique Values

35.	Generate 10 random numbers and sort them.

In [41]:
import numpy as np

arr = np.random.rand(10)

print("Original:", arr)
print("Sorted:", np.sort(arr))

Original: [0.82971531 0.09956015 0.57483114 0.52218289 0.91070855 0.57220291
 0.03743163 0.87001546 0.13110156 0.25825175]
Sorted: [0.03743163 0.09956015 0.13110156 0.25825175 0.52218289 0.57220291
 0.57483114 0.82971531 0.87001546 0.91070855]


36.	Given an array containing repeated values, find its unique elements.

In [42]:
import numpy as np

arr = np.array([1, 2, 2, 3, 4, 4, 5, 5])

print(np.unique(arr))

[1 2 3 4 5]


37.	Given an array of student marks, find the unique marks.

In [43]:
import numpy as np

marks = np.array([45, 67, 78, 45, 89, 67, 92, 78, 56, 89])

print(np.unique(marks))

[45 56 67 78 89 92]


38.	Use np.in1d() to check whether selected values occur in an array.

In [45]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
values = np.array([20, 40, 60])

print(np.in1d(values, arr))

[ True  True False]


/tmp/ipykernel_2912/1543095711.py:6: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  print(np.in1d(values, arr))


#11. Integrated Lab Questions

39.	Student Marks Analysis: Create a NumPy array containing marks of 10 students in 3 subjects. Calculate each student's total and average marks. Identify students whose average is ≥ 50 using np.where().

In [46]:
import numpy as np

marks = np.array([[60, 70, 80],
                  [45, 55, 65],
                  [30, 40, 50],
                  [75, 85, 90],
                  [50, 60, 70],
                  [35, 45, 40],
                  [80, 75, 85],
                  [55, 65, 60],
                  [40, 50, 45],
                  [90, 85, 95]])

total = np.sum(marks, axis=1)
average = np.mean(marks, axis=1)

result = np.where(average >= 50, "Yes", "No")

print("Total:", total)
print("Average:", average)
print("Average >= 50:", result)

Total: [210 165 120 250 180 120 240 180 135 270]
Average: [70.         55.         40.         83.33333333 60.         40.
 80.         60.         45.         90.        ]
Average >= 50: ['Yes' 'Yes' 'No' 'Yes' 'Yes' 'No' 'Yes' 'Yes' 'No' 'Yes']


40.	Matrix Analysis: Create a 4 × 4 matrix containing numbers 1–16. Find its transpose, row-wise sums, column-wise sums, mean, maximum, and minimum. Extract the central 2 × 2 matrix.

In [47]:
import numpy as np

matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

print("Transpose:")
print(matrix.T)

print("Row-wise sum:", np.sum(matrix, axis=1))
print("Column-wise sum:", np.sum(matrix, axis=0))
print("Mean:", np.mean(matrix))
print("Maximum:", np.max(matrix))
print("Minimum:", np.min(matrix))

print("Central 2x2:")
print(matrix[1:3, 1:3])

Transpose:
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
Row-wise sum: [10 26 42 58]
Column-wise sum: [28 32 36 40]
Mean: 8.5
Maximum: 16
Minimum: 1
Central 2x2:
[[ 6  7]
 [10 11]]


41.	Random Data Analysis: Generate 20 observations using np.random.randn(). Calculate the mean, standard deviation, minimum, maximum, and sorted values. Replace all negative observations with zero using np.where().

In [48]:
import numpy as np

arr = np.random.randn(20)

print("Array:", arr)
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))
print("Minimum:", np.min(arr))
print("Maximum:", np.max(arr))
print("Sorted:", np.sort(arr))

arr = np.where(arr < 0, 0, arr)

print("After replacing negative values:", arr)

Array: [-0.33251011  0.81283791  1.45814032 -1.1670413  -0.28499988  0.46528328
  1.81538311 -1.18260075  0.75718912 -0.2882598   0.92829244 -0.27791966
  1.75291014  0.75578635  0.00335384 -0.4843957   1.35300458  0.16153143
  1.0114707   1.35317033]
Mean: 0.43053131702827185
Standard Deviation: 0.8868192037123003
Minimum: -1.182600753854047
Maximum: 1.8153831091266637
Sorted: [-1.18260075 -1.1670413  -0.4843957  -0.33251011 -0.2882598  -0.28499988
 -0.27791966  0.00335384  0.16153143  0.46528328  0.75578635  0.75718912
  0.81283791  0.92829244  1.0114707   1.35300458  1.35317033  1.45814032
  1.75291014  1.81538311]
After replacing negative values: [0.         0.81283791 1.45814032 0.         0.         0.46528328
 1.81538311 0.         0.75718912 0.         0.92829244 0.
 1.75291014 0.75578635 0.00335384 0.         1.35300458 0.16153143
 1.0114707  1.35317033]


42.	Matrix Operations Challenge: Create two 3 × 3 matrices and perform element-wise addition, element-wise multiplication, matrix multiplication, transpose of the first matrix, and maximum/minimum of the resulting matrix.

In [49]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

b = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

addition = a + b
multiplication = a * b
matrix_product = np.dot(a, b)
transpose = a.T

print("Addition:")
print(addition)

print("Element-wise Multiplication:")
print(multiplication)

print("Matrix Multiplication:")
print(matrix_product)

print("Transpose:")
print(transpose)

print("Maximum:", np.max(matrix_product))
print("Minimum:", np.min(matrix_product))

Addition:
[[10 10 10]
 [10 10 10]
 [10 10 10]]
Element-wise Multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
Matrix Multiplication:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Transpose:
[[1 4 7]
 [2 5 8]
 [3 6 9]]
Maximum: 138
Minimum: 18


43.	Array Manipulation Challenge: Create an array containing 1–24, reshape it into a 4 × 6 matrix, extract selected rows and columns, transpose it, calculate row/column statistics, and identify unique values.

In [50]:
import numpy as np

arr = np.arange(1, 25).reshape(4, 6)

print("Matrix:")
print(arr)

print("Selected rows:")
print(arr[1:3])

print("Selected columns:")
print(arr[:, 1:3])

print("Transpose:")
print(arr.T)

print("Row sums:", np.sum(arr, axis=1))
print("Column sums:", np.sum(arr, axis=0))

print("Row mean:", np.mean(arr, axis=1))
print("Column mean:", np.mean(arr, axis=0))

print("Unique values:", np.unique(arr))

Matrix:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Selected rows:
[[ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
Selected columns:
[[ 2  3]
 [ 8  9]
 [14 15]
 [20 21]]
Transpose:
[[ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]
 [ 6 12 18 24]]
Row sums: [ 21  57  93 129]
Column sums: [40 44 48 52 56 60]
Row mean: [ 3.5  9.5 15.5 21.5]
Column mean: [10. 11. 12. 13. 14. 15.]
Unique values: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
